name: eigenscore-py310
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.8.0
      - torchvision==0.23.0
      - torchaudio==2.11.0
      - transformers==5.3.0
      - pandas==2.3.3
      - tqdm==4.67.1
      - scikit-learn==1.7.2
      - matplotlib==3.10.6
      - rouge_score==0.1.2
      - sentence-transformers==5.5.1
      - datasets==5.0.1
      - ipdb==0.13.13
      - accelerate==1.13.0
      - torchmetrics==1.9.0
      - evaluate==0.4.6
      - openai==0.28.1
      - pandarallel==1.6.5
      - persist-to-disk==0.0.7